### PR TITLE
Add generic history of resources history

### PR DESCRIPTION
**Pull request by ad-m**
Missing endpoints:
```
https://api.hyperone.com/v1/dns/zone/x./queue --> 404
https://api.hyperone.com/v1/vm/test-vm2/queue --> missing name resolution
https://api.hyperone.com/v1/firewall/my-firewall/queue --> missing name resolution
https://api.hyperone.com/v1/netgw/5784e97be2627505227b579f/queue --> 404
https://api.hyperone.com/v1/netgw/my-netgw/queue --> missing name resolution
https://api.hyperone.com/v1/network/my-net/queue --> missing name resolution
https://api.hyperone.com/v1/network/my-net/ip/5b322659fd00bea6799c4bad/queue --> 404 (changes not available via network)
https://api.hyperone.com/v1/vault/my-vault/queue --> 404
https://api.hyperone.com/v1/snapshot/my-snapshot/queue --> 404
https://api.hyperone.com/v1/snapshot/my-snapshot/queue --> missing name resolution
https://api.hyperone.com/v1/tenant/5af0bbbcb7802508ad844caa/credential/authtoken/6e3e03f4b865481fbbe5472889fbb205/queue --> 404 (Useful to provide some information about changes in access of token)
```

New commands:
```bash
$ grep '```.*history' docs/ -R
docs/snapshot.md:```h1 snapshot history | --snapshot SNAPSHOT```
docs/vm.md:```h1 vm history | --vm VM```
docs/vm.md:```h1 vm nic history | --nic NIC --vm VM```
docs/ip.md:```h1 ip history | --ip IP```
docs/image.md:```h1 image history | --image IMAGE```
docs/netgw.md:```h1 netgw history | --netgw NETGW```
docs/network.md:```h1 network history | --network NETWORK```
docs/network.md:```h1 network ip history | --ip IP --network NETWORK```
docs/disk.md:```h1 disk history | --disk DISK```
docs/firewall.md:```h1 firewall history | --firewall FIREWALL```
docs/vault.md:```h1 vault history | --vault VAULT```
docs/dns.md:```h1 dns zone history | --zone ZONE```
docs/iso.md:```h1 iso history | --iso ISO```
docs/project.md:```h1 project history | --project PROJECT```
docs/project.md:```h1 project token history | --token TOKEN --project PROJECT```
```

Skipped commands:
```bash
$ grep 'commands:' bin/ -R
bin/project/token/access/index.js:        commands: ['list', 'delete'],
bin/project/token/index.js:        commands: ['list', 'delete', 'history'],
bin/vault/credential/index.js:        commands: [],
bin/vault/credential/password/index.js:        commands: ['list', 'delete'],
bin/vault/credential/certificate/index.js:        commands: ['list', 'delete'],
bin/image/index.js:    commands: ['show', 'delete', 'rename', 'history'],
bin/service/index.js:    commands: [ 'show' ],
bin/generic/defaults.js:    commands: ['list', 'show', 'delete', 'history'],
bin/generic/credentials/index.js:        commands: ['list', 'delete'],
bin/vm/dvd/index.js:    commands: ['list'],
bin/vm/index.js:    commands: [ 'list', 'show', 'history'],
bin/vm/disk/index.js:    commands: ['list'],
bin/vm/nic/ip/index.js:    commands: [ 'list', 'delete' ],
bin/vm/tag/index.js:    commands: [ 'list', 'show' ],
bin/vm/tag/index.js:    commands: ['list'],
```

### CODE REVIEW

**Comment by fredericosilva** [comment]
@ad-m resource "missing name resolution" is fixed

**Comment by ad-m** [comment]
@fredericosilva , ok, so I will tests soon what is missing. Maybe we will use tests for that even ;)

**Comment by ad-m** [comment]
@fredericosilva , missing history of firewall.

```
$ h1 firewall history --firewall 5b3a0750db77e0540811669f | wc -l
0
```

**Comment by ad-m** [comment]
```
{
    cmd: {
      cmd: 'vm nic history --vm 5b3a1edd31d5ee90eeeef650 --nic 00155DFF0B55',
      history: [],
    },
    err: Error {
      handler: Function handler {},
      node: Command {
        config: Object { … },
        description: 'History of nic',
        epilog: undefined,
        handler: Function handler {},
        name: 'history',
        optionGroups: Object { … },
        options: Object { … },
        params: {},
        parent: Category { … },
        plugins: Array [ … ],
        plugins$: Promise { … },
        version: undefined,
      },
      original: null,
      parser: ArgumentParser {
        _actionGroups: Array [ … ],
        _actions: Array [ … ],
        _defaults: Object { … },
        _hasNegativeNumberOptionals: [],
        _mutuallyExclusiveGroups: [],
        _optionStringActions: Object { … },
        _optionals: ArgumentGroup { … },
        _positionals: ArgumentGroup { … },
        _regexpNegativeNumber: /^[-]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$/,
        _registries: Object { … },
        _subparsers: null,
        argumentDefault: null,
        conflictHandler: 'error',
        debug: false,
        description: 'History of nic',
        epilog: undefined,
        formatterClass: Function CustomHelpFormatter { … },
        fromfilePrefixChars: null,
        prefixChars: '-',
        prog: 'h1 vm nic history',
        usage: undefined,
        version: undefined,
      },
      response: Response {
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        accepted: false,
        badRequest: true,
        body: Object { … },
        buffered: true,
        charset: 'utf-8',
        clientError: true,
        error: Error { … },
        files: undefined,
        forbidden: false,
        header: Object { … },
        headers: Object { … },
        info: false,
        links: {},
        noContent: false,
        notAcceptable: false,
        notFound: false,
        ok: false,
        redirect: false,
        redirects: [],
        req: ClientRequest { … },
        request: Request { … },
        res: IncomingMessage { … },
        serverError: false,
        setEncoding: Function bound  {},
        status: 400,
        statusCode: 400,
        statusType: 4,
        text: '{"status":400,"message":"netadp \\"00155DFF0B55\\" is ambiguous"}',
        type: 'application/json',
        unauthorized: false,
      },
      status: 400,
      message: 'Bad Request',
    },
    history: [],
  }
```

**Pull request merged**
