### PR TITLE
Add tests for Registry; Add domain management to Registry

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by fredericosilva** [comment]
@ad-m rebase please

**Comment by fredericosilva** [comment]
LGTM, waiting for the rebase

**Comment by ad-m** [comment]
It would be nice add support for the "show" command too & uncomment tests for that. Do you see a big problem in this?

**Comment by fredericosilva** [comment]
@ad-m endpoint exposed [docs](https://api.hyperone.com/docs#operation/registry_get_repository_repositoryId)

**Comment by ad-m** [comment]
@fredericosilva , enabled, rebased, docs updated. Tests verified.

**Pull request merged**
