### PR TITLE
Drop delay in tests

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by ad-m** [comment]
Deploy to tests. After discussion, i think that delay should not be necessary.

**Comment by fredericosilva** [comment]
@ad-m is that an API bug?

**Comment by ad-m** [comment]
There is no problem with manual calling. Requires investigation.

```
$ h1 vm create --name test-vm --os-disk ssd,10 --type a1.nano --image debian --ssh so-wp; \
  h1 vm show --vm test-vm; \
  h1 vm stop --vm test-vm; \
  h1 vm show --vm test-vm; \
  h1 vm start --vm test-vm; \
  h1 vm show --vm test-vm; \
  h1 vm delete --yes --vm test-vm;
ID                        NAME     FLAVOUR  STATE    PROCESSING
5b390053db77e054081121d9  test-vm  a1.nano  Running  false

ID                        NAME     FLAVOUR  STATE    PROCESSING
5b390053db77e054081121d9  test-vm  a1.nano  Running  false

ID                        NAME     FLAVOUR  STATE  PROCESSING
5b390053db77e054081121d9  test-vm  a1.nano  Off    false

ID                        NAME     FLAVOUR  STATE  PROCESSING
5b390053db77e054081121d9  test-vm  a1.nano  Off    false

ID                        NAME     FLAVOUR  STATE    PROCESSING
5b390053db77e054081121d9  test-vm  a1.nano  Running  false

ID                        NAME     FLAVOUR  STATE    PROCESSING
5b390053db77e054081121d9  test-vm  a1.nano  Running  false

ID                        NAME     FLAVOUR  STATE   PROCESSING
5b390053db77e054081121d9  test-vm  a1.nano  Delete  false
```

**Comment by fredericosilva** [comment]
@ad-m should be fixed now

**Pull request merged**
