### PR TITLE
Allows to create VM with multiple disks

### PR DESCRIPTION
**Pull request by ad-m**
Because of internal needs.

### CODE REVIEW

**Comment by fredericosilva** [comment]
Is this a breaking change?

**Comment by gregorybrzeski** [comment]
I think we should discuss this as os-disk (first disk) management is tricky already.

Scenario:

- vm with os-disk and **two** additional data-disks

How to change **only** an os-disk for another one ?

We have an assumption that first disk on the disk **array** is a os-disk, therefore:

- should a user detach all disks then add the new os-disk and re attach data-disks ?
- detach os-disk, then how to re-attach a new os-disk without detaching data-disks ?

**Comment by ad-m** [comment]
@fredericosilva , no, there is no breaking change.

**Comment by ad-m** [comment]
HyperOne has developed a new version of CLI v2 which is a complete rewrite of this software. The problem you indicated concerns the V1 version, which is not further developed. The reported problem should apply generic solution for that problem and no longer apply to V2.

Feel free to ask if you have additional comments.

**Pull request closed without merging**
