### PR TITLE
[WIP] Update 'vm ssh' to use dns

### PR DESCRIPTION
**Pull request by ad-m**
Missing scoping due missing property on public API.

### CODE REVIEW

**Comment by gregorybrzeski** [comment]
We need to document publicly the dns "logic" for returning the ip address for a VM. 

Should dns resolving logic should be part of reference documentation for a resource ?

**Comment by ad-m** [comment]
I see that we should document it. However, it is not ready for production use yet, as it is not completed and will be subject to change (https://app.asana.com/0/816841216465133/823375683209529).

**Comment by gregorybrzeski** [comment]
Should we wait with this PR until it's ready for production use and completed  ?

Looking at the asana task which you reverence it well overdue :)

The question remains, should it be documented in reference documentation for a resource or in some other place. I strongly believe that reference documentation is the right place for such documentation. 

There is also a need for "concept" document to give some background/context for dns resolution for resources.

**Comment by ad-m** [comment]
As I said before:
> I see that we should document it.
I also agree that this should be documented in the reference documentation and concept document. As far as the concept document is concerned, I see that it will require considering how it should be published, because it is not service-oriented content.

**Comment by ad-m** [comment]
Should DNS for VM be available on private networks to ensure name resolution using private addresses?

**Pull request merged**
